### ISSUE TITLE
Question: Make JSON schemas publicly available

### ISSUE THREAD

**Issue by xeladotbe** [alexa/apl-suggester#6]
I'm using the defined JSON schemas to provide autocompletion in my editor on [apl.ninja](https://apl.ninja). Since the schemas are not exported I've to awkwardly include them via imports similar to "import { JSON_SCHEMA as XXX } from 'apl-suggester/dist/src/assets/xxx';" into my project, would you be willing to export them so that I can import them normally like: import { ... } from 'apl-suggester/schemes' ?

https://user-images.githubusercontent.com/11685228/104224400-38f52a80-5445-11eb-90c3-aab92612170a.mp4

Thank you and regards,
Alex

**Comment by rmtuckerphx** [comment]
I agree

**Comment by jamescryptoji** [comment]
Hi there,

Apologies for the delayed response. The reason was that team had been considering a major refactoring to APL Suggester, and can't commit to say yes until the feature can actually be released.

We ended up building a new project that no longer validates by atomic schemas, and this ask is achieved there. Once we sort out all internal process, we will open source it. As for APL Suggester, there is no plan to add new features, only spec updates will be done with major APL releases.

Thank you.
